name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    # using Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - uses: actions/cache@v3 # this allows for re-using node_modules caching, making builds a bit faster.
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: NPM Install Angular
        run: npm install -g @angular/cli@11.2.8 > /dev/null
      - name: NPM Install
        run: npm install
      - name: NPM build Angular Production
        run: npm run build
      # - name: Test
      #   run: npm run test:ci
      # - name: Test coverage
      #   run: npm run test:ci:cov
      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.QUICKLABS_P_KEY }}
          SOURCE: "/web/core/dist/"
          REMOTE_HOST: "ec2-35-87-28-156.us-west-2.compute.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/var/www/html/quicklabs-core/"